config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount Thredded::Engine => '/home'

  get '/admin', to: 'admin#index'

  namespace :admin do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts

    resources :users do
      resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
    end
  end

  resources :users do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
  end

  get '/library', to: 'library#index', as: :library

  scope('/stack') do
    get '/import', to: 'stack#import', as: :notes_import
    post '/import', to: 'bookmarks#bulk_upload', as: :bookmarks_import
    get '/list', to: 'stack#list', as: :offline_note_list
    get '/sync', to: 'stack#sync', as: :sync_library
    get '/', to: 'stack#index'
  end

  get '/messaging', to: 'stack#messaging', as: :messages
  get '/about', to: 'home#index'
  get '/me', to: 'users#me', as: :me
  root to: redirect('/home')
end

app/models/collection.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: collections
#
#  id          :bigint           not null, primary key
#  description :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_collections_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Collection < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/collections_controller.rb
# frozen_string_literal: true

module Admin
  class CollectionsController < ApplicationController
    before_action :set_collection, only: %i[show edit update destroy]

    # GET /collections or /collections.json
    def index
      @collections = Collection.all
    end

    # GET /collections/1 or /collections/1.json
    def show; end

    # GET /collections/new
    def new
      @collection = Collection.new
    end

    # GET /collections/1/edit
    def edit; end

    # POST /collections or /collections.json
    def create
      @collection = Collection.new(collection_params)

      respond_to do |format|
        if @collection.save
          format.html { redirect_to collection_url(@collection), notice: 'Collection was successfully created.' }
          format.json { render :show, status: :created, location: @collection }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @collection.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /collections/1 or /collections/1.json
    def update
      respond_to do |format|
        if @collection.update(collection_params)
          format.html { redirect_to collection_url(@collection), notice: 'Collection was successfully updated.' }
          format.json { render :show, status: :ok, location: @collection }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @collection.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /collections/1 or /collections/1.json
    def destroy
      @collection.destroy

      respond_to do |format|
        format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:title, :description, :user_id)
    end
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[show edit update destroy]

  # GET /collections or /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show; end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit; end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def collection_params
    params.require(:collection).permit(:title, :description, :user_id)
  end
end

app/helpers/collections_helper.rb
# frozen_string_literal: true

module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: [current_user, collection], local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', user_collection_path(id: @collection.id, user_id: @collection.user_id) %> |
<%= link_to 'Back', user_collections_path(user_id: @collection.user_id) %>

app/views/collections/index.html.erb
<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.title %></td>
        <td><%= collection.description %></td>
        <td><%= collection.user_id %></td>
        <td><%= link_to 'Show', user_collection_path(collection) %></td>
        <td><%= link_to 'Edit', edit_user_collection_path(collection) %></td>
        <td><%= button_to 'Destroy', user_collection_path(collection), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_user_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back to your collections', user_collections_path(user_id: current_user) %>

app/views/collections/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @collection.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @collection.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @collection.user_id %>
</p>

<%= link_to 'Edit', edit_user_collection_path(id: @collection.id, user_id: @collection.user_id) %> |
<%= link_to 'Back', user_collections_path(user_id: @collection.user_id) %>