config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount Thredded::Engine => '/home'

  get '/admin', to: 'admin#index'

  namespace :admin do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts

    resources :users do
      resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
    end
  end

  resources :users do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
  end

  get '/library', to: 'library#index', as: :library

  scope('/stack') do
    get '/import', to: 'stack#import', as: :notes_import
    post '/import', to: 'bookmarks#bulk_upload', as: :bookmarks_import
    get '/list', to: 'stack#list', as: :offline_note_list
    get '/sync', to: 'stack#sync', as: :sync_library
    get '/', to: 'stack#index'
  end

  get '/messaging', to: 'stack#messaging', as: :messages
  get '/about', to: 'home#index'
  get '/me', to: 'users#me', as: :me
  root to: redirect('/home')
end

app/models/note.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: notes
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_notes_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Note < ApplicationRecord
  belongs_to :user
  has_many :bookmarks_notes, dependent: :destroy
  has_many :bookmarks, through: :bookmarks_notes, dependent: :destroy
end

app/controllers/admin/notes_controller.rb
# frozen_string_literal: true

module Admin
  class NotesController < ApplicationController
    before_action :set_note, only: %i[show edit update destroy]
    load_and_authorize_resource

    # GET /notes or /notes.json
    def index
      @notes = filter_optionally(Note.all, :links, :related_link)
    end

    # GET /notes/1 or /notes/1.json
    def show; end

    # GET /notes/new
    def new
      @note = Note.new
    end

    # GET /notes/1/edit
    def edit; end

    # POST /notes or /notes.json
    def create
      current_params = note_params
      tag_attributes = current_params.delete(:tags)
      @note          = Note.new(current_params)

      if tag_attributes.present?
        tags = tag_attributes.map { |tag| { user_id: tag[:user_id], title: tag[:title] } }
        @note.tags << tags.map { |tag| Tag.create!(tag) }
      end

      respond_to do |format|
        if @note.save
          format.html { redirect_to note_url(@note), notice: 'Note was successfully created.' }
          format.json { render :show, status: :created, location: @note }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @note.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /notes/1 or /notes/1.json
    def update
      respond_to do |format|
        if @note.update(note_params)
          format.html { redirect_to note_url(@note), notice: 'Note was successfully updated.' }
          format.json { render :show, status: :ok, location: @note }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @note.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /notes/1 or /notes/1.json
    def destroy
      @note.destroy

      respond_to do |format|
        format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def filter_optionally(collection, filter_field, param_name)
      user_input = params[param_name]
      return collection if user_input.blank?

      filter_params = {}

      filter_params[filter_field] = { id: user_input }

      collection.joins(filter_field).where(**filter_params)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      initial_params                = params.require(:note).permit(:user_id, :title, :content, :tags)
      associated_tags_for_this_note = initial_params.delete(:tags)

      return initial_params if associated_tags_for_this_note.blank?

      initial_params[:tags] = associated_tags_for_this_note.split(',').map do |tag|
        { user_id: current_user.id, title: tag }
      end
    end
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /notes or /notes.json
  def index
    @notes = filter_optionally(Note.all, :links, :related_link)
  end

  # GET /notes/1 or /notes/1.json
  def show; end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit; end

  # POST /notes or /notes.json
  def create
    current_params = note_params
    tag_attributes = current_params.delete(:tags)
    @note          = Note.new(current_params)

    if tag_attributes.present?
      tags = tag_attributes.map { |tag| { user_id: tag[:user_id], title: tag[:title] } }
      @note.tags << tags.map { |tag| Tag.create!(tag) }
    end

    respond_to do |format|
      if @note.save
        format.html { redirect_to user_note_url(user_id: current_user, id: @note), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to user_note_url(user_id: current_user, id: @note), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to user_notes_url(current_user), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def filter_optionally(collection, filter_field, param_name)
    user_input = params[param_name]
    return collection if user_input.blank?

    filter_params = {}

    filter_params[filter_field] = { id: user_input }

    collection.joins(filter_field).where(**filter_params)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def note_params
    initial_params                = params.require(:note).permit(:user_id, :title, :content, :tags)
    associated_tags_for_this_note = initial_params.delete(:tags)

    return initial_params if associated_tags_for_this_note.blank?

    initial_params[:tags] = associated_tags_for_this_note.split(',').map do |tag|
      { user_id: current_user.id, title: tag }
    end
  end
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: [current_user, note], local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field hidden-none-display">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.user_id %></td>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%= link_to 'Show', user_note_path(id: note.id, user_id: note.user_id) %></td>
        <td><%= link_to 'Edit', edit_user_note_path(id: note.id, user_id: note.user_id) %></td>
        <td><%= button_to 'Destroy', user_note_path(id: note.id, user_id: note.user_id), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_user_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', user_notes_path(user_id: current_user) %>

app/views/notes/show.html.erb
<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<%= link_to 'Edit', edit_user_note_path(id: @note.id, user_id: @note.user_id) %> |
<%= link_to 'Back', user_notes_path(user_id: current_user) %>