config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount Thredded::Engine => '/home'

  get '/admin', to: 'admin#index'

  namespace :admin do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts

    resources :users do
      resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
    end
  end

  resources :users do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
  end

  get '/library', to: 'library#index', as: :library

  scope('/stack') do
    get '/import', to: 'stack#import', as: :notes_import
    post '/import', to: 'bookmarks#bulk_upload', as: :bookmarks_import
    get '/list', to: 'stack#list', as: :offline_note_list
    get '/sync', to: 'stack#sync', as: :sync_library
    get '/', to: 'stack#index'
  end

  get '/messaging', to: 'stack#messaging', as: :messages
  get '/about', to: 'home#index'
  get '/me', to: 'users#me', as: :me
  root to: redirect('/home')
end

app/models/reminder.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: reminders
#
#  id            :bigint           not null, primary key
#  due           :datetime
#  excerpt       :string
#  reminder_type :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint           not null
#
# Indexes
#
#  index_reminders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Reminder < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/reminders_controller.rb
# frozen_string_literal: true

module Admin
  class RemindersController < ApplicationController
    before_action :set_reminder, only: %i[show edit update destroy]

    # GET /reminders or /reminders.json
    def index
      @reminders = Reminder.all
    end

    # GET /reminders/1 or /reminders/1.json
    def show; end

    # GET /reminders/new
    def new
      @reminder = Reminder.new
    end

    # GET /reminders/1/edit
    def edit; end

    # POST /reminders or /reminders.json
    def create
      @reminder = Reminder.new(reminder_params)

      respond_to do |format|
        if @reminder.save
          format.html { redirect_to reminder_url(@reminder), notice: 'Reminder was successfully created.' }
          format.json { render :show, status: :created, location: @reminder }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @reminder.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /reminders/1 or /reminders/1.json
    def update
      respond_to do |format|
        if @reminder.update(reminder_params)
          format.html { redirect_to reminder_url(@reminder), notice: 'Reminder was successfully updated.' }
          format.json { render :show, status: :ok, location: @reminder }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @reminder.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /reminders/1 or /reminders/1.json
    def destroy
      @reminder.destroy

      respond_to do |format|
        format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_params
      params.require(:reminder).permit(:due, :excerpt, :user_id, :type)
    end
  end
end

app/controllers/reminders_controller.rb
# frozen_string_literal: true

class RemindersController < ApplicationController
  before_action :set_reminder, only: %i[show edit update destroy]

  # GET /reminders or /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1 or /reminders/1.json
  def show; end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit; end

  # POST /reminders or /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to reminder_url(@reminder), notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1 or /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to reminder_url(@reminder), notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1 or /reminders/1.json
  def destroy
    @reminder.destroy

    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def reminder_params
    params.require(:reminder).permit(:due, :excerpt, :user_id, :type)
  end
end

app/helpers/reminders_helper.rb
# frozen_string_literal: true

module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= form_with(model: [current_user, reminder], local: true) do |form| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
        <% reminder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :due %>
    <%= form.datetime_select :due %>
  </div>

  <div class="field">
    <%= form.label :excerpt %>
    <%= form.text_field :excerpt %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<h1>Reminders</h1>

<table>
  <thead>
    <tr>
      <th>Due</th>
      <th>Excerpt</th>
      <th>User</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.due %></td>
        <td><%= reminder.excerpt %></td>
        <td><%= reminder.user_id %></td>
        <td><%= reminder.type %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= button_to 'Destroy', reminder, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Reminder', new_user_reminder_path(current_user) %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>
<%= link_to 'Back', user_reminders_path(current_user) %>

app/views/reminders/show.html.erb
<p>
  <strong>Due:</strong>
  <%= @reminder.due %>
</p>

<p>
  <strong>Excerpt:</strong>
  <%= @reminder.excerpt %>
</p>

<p>
  <strong>User:</strong>
  <%= @reminder.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @reminder.type %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', user_reminders_path(current_user) %>