config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount Thredded::Engine => '/home'

  get '/admin', to: 'admin#index'

  namespace :admin do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts

    resources :users do
      resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
    end
  end

  resources :users do
    resources :tags, :collections, :bookmarks, :reminders, :notes, :posts
  end

  get '/library', to: 'library#index', as: :library

  scope('/stack') do
    get '/import', to: 'stack#import', as: :notes_import
    post '/import', to: 'bookmarks#bulk_upload', as: :bookmarks_import
    get '/list', to: 'stack#list', as: :offline_note_list
    get '/sync', to: 'stack#sync', as: :sync_library
    get '/', to: 'stack#index'
  end

  get '/messaging', to: 'stack#messaging', as: :messages
  get '/about', to: 'home#index'
  get '/me', to: 'users#me', as: :me
  root to: redirect('/home')
end

app/models/tag.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tags_on_title_and_user_id  (title,user_id) UNIQUE
#  index_tags_on_user_id            (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Tag < ApplicationRecord
  validates :title, uniqueness: { scope: :user_id }
  validates :title, presence: true

  has_many :subject_links, foreign_key: :subject_id, class_name: 'LinkedTag', dependent: :destroy, inverse_of: :subject
  has_many :object_links, foreign_key: :object_id, class_name: 'LinkedTag', dependent: :destroy, inverse_of: :object

  has_many :objects, through: :subject_links, dependent: :destroy
  has_many :subjects, through: :object_links, dependent: :destroy

  accepts_nested_attributes_for :subjects, :objects

  delegate :to_s, to: :title

  belongs_to :user

  # Retrieves `subjects` of this tag whose linked_tag intermediate model has the corresponding `relationship`
  def subjects_with_predicate(relationship = nil)
    links          = LinkedTag.select(:subject_id, :predicate).where(id: object_links)
    filtered_links = relationship.nil? ? links : links.filter { |link| link.predicate == relationship }

    filtered_links.map do |current_link|
      current_predicate = current_link.predicate
      current_subject   = subjects.find(current_link.subject_id)

      { subject: current_subject, relationship: current_predicate }
    end
  end
end

app/controllers/admin/tags_controller.rb
# frozen_string_literal: true

module Admin
  class TagsController < ApplicationController
    before_action :set_tag, only: %i[show edit update destroy]

    # GET /tags or /tags.json
    def index
      @tags = Tag.all
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags or /tags.json
  def index
    @tags = if params[:note_id]
              Tag.joins(:notes).where(notes: { id: params[:note_id] })
            else
              Tag.all
            end
  end

  # GET /tags/1 or /tags/1.json
  def show; end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to user_tag_url(user_id: @tag.user_id, id: @tag.id), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to user_tag_url(@tag), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to user_tags_path(user_id: current_user&.id), notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:title, :user_id)

    # params.require(:tag).permit(:title, :user_id, :object_links)
  end
end

app/helpers/admin/users/tags_helper.rb
# frozen_string_literal: true

module Admin
  module Users
    module TagsHelper
    end
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: [current_user, tag], local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <%= form.fields_for :object_links do |subject_subform| %>
    <div class="field">
      <p>Link this tag to another:</p>
      <%= subject_subform.label :new_related_tag %>
      <%= subject_subform.text_field :new_related_tag %>
      <%= subject_subform.label :existing_related_tag %>
      <%= subject_subform.select :existing_related_tag, current_user.tags, {}, { multiple: true } %>
    </div>

  <%- end %>
  <div class="field hidden-none-display">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', user_tag_path(id: @tag, user_id: @tag.user_id) %> |
<%= link_to 'Back', user_tags_path(@tag.user_id) %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= tag.user_id %></td>
        <td><%= link_to 'Show', user_tag_path(id: tag, user_id: tag.user_id) %></td>
        <td><%= link_to 'Edit', edit_user_tag_path(id: tag, user_id: tag.user_id) %></td>
        <td><%= button_to 'Destroy', user_tag_path(id: tag, user_id: tag.user_id), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%- if current_user %>
  <%= link_to 'New Tag', new_user_tag_path(user_id: current_user) %>
<%- end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', user_tags_path(user_id: current_user.id) %>

app/views/tags/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tag.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @tag.user_id %>
</p>
<p>
  <strong>Subjects:</strong>
    <%- @tag.subjects.each do |subject| %>
      <%= subject %>
    <%- end %></p>
<p>
  <strong>Objects:</strong>
  <%- @tag.objects.each do |object| %>
    <%= object %>
  <%- end %>
</p>

<%= link_to 'Edit', Rails.application.routes.url_helpers.edit_user_tag_path(user_id: @tag.user_id, id: @tag.id) %> |
<%= link_to 'Back', user_tags_path(@tag.user_id) %>